### ISSUE TITLE
movement speed and rigid moves

### ISSUE THREAD

**Issue by bandric1** [mashurex/ctc-dual-bttskr14t-marlin#1]
Hi friend how did you solve the movement issues. I have an issue with extruder also i have an aluminum one am feeding filament from the top thru hole printer is in cabinet. I used TMC 2130 drivers since there is a lot of space under i stacked a good fan to keep them cool. The 2130 are running in SPI mode and are quite smooth and silent only when motion is switching it kind of bumps i cant correctly explain in words there is no smooth movement as in C- ENDER-3P but its high speed stop.
And also what are your steps/mm on extruder i measured it and calculated it but sometimes it just stops extruding in the middle of the print after 5 mm of print in height.

**Comment by mashurex** [comment]
Apologies for taking over a year to reply!
I'm running the 2208 stepper drivers in SPI but I do not have any experience with 2130 at all. 

I think I understand what you mean by rigid moves as in:

- When the toolhead switches directions it can do it very sharply and it is much noisier than normal
- When the printer is actually extruding (not traveling or retracting) everything is generally smoother and more quiet

If that's pretty much the case I would think it's possibly a combination of:

- The VERY FIRST THING I would check is the VRef voltage value on the stepper driver. You will need to lookup exactly what the appropriate value is and make sure that the 2130 driver has the correct value
- Make sure you also have the right X_CURRENT, Y_CURRENT, E_CURRENT (also E2_CURRENT if dual), and Z_CURRENT values in `Configuration_adv.h` 
- I also enabled `TMC_DEBUG` and `MONITOR_DRIVER_STATUS` when I was first setting everything up
- If you don't have Stealth Chop/Spread Cycle enabled for the X and Y steppers, enable it (I do not enable it for my E and Z steppers)
- If you have SC enabled, you can raise the threshold so that it will stay quieter at higher speeds (at the cost of acceleration and torque)
- If you are using junction deviation or jerk settings, you want to calibrate them and smooth them out
- If Junction/Jerk settings are calibrated you may want to reduce your firmware max acceleration settings at least in the X and Y

As for the extruder sometimes just stopping - I haven't seen that. But I have had, randomly a couple of times where when I go to print the head does not move at all (no X, Y, or Z) after the print starts. It still extrudes, it just doesn't move the head anymore after homing. If I cancel the print and re-print it prints just fine! I'm not sure if it is OctoPi or something else but it has only happened a couple of times. 

It's possible that if you have not set the E_CURRENT and/or VRef on the E driver(s) that the stepper gets too hot around that time. I would put your hand to the stepper and check the temp on it after it's been printing a while. I would be careful, if it is over-driving it can be hot enough to actually burn you. It's okay for it to be warm, but it should never be hot. If it is hot you need to lower the VRef.
